// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSkcWoT0ojKPctWfcJwSinXbDiFlJPNA0',
    appId: '1:839283635148:web:303046fd02c66c0a782369',
    messagingSenderId: '839283635148',
    projectId: 'chatting-app-flutter-be3fd',
    authDomain: 'chatting-app-flutter-be3fd.firebaseapp.com',
    storageBucket: 'chatting-app-flutter-be3fd.firebasestorage.app',
    measurementId: 'G-MM7VCCKP4S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC55A4SCvBNqUuLwuTvf7jfkrfQ4-a5Lv8',
    appId: '1:839283635148:android:93172e509f9c0051782369',
    messagingSenderId: '839283635148',
    projectId: 'chatting-app-flutter-be3fd',
    storageBucket: 'chatting-app-flutter-be3fd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByQ8pJXTH-kKHsvmNxmpk67wtCasabO1A',
    appId: '1:839283635148:ios:149d51aa73703f9a782369',
    messagingSenderId: '839283635148',
    projectId: 'chatting-app-flutter-be3fd',
    storageBucket: 'chatting-app-flutter-be3fd.firebasestorage.app',
    iosBundleId: 'com.example.chattingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByQ8pJXTH-kKHsvmNxmpk67wtCasabO1A',
    appId: '1:839283635148:ios:149d51aa73703f9a782369',
    messagingSenderId: '839283635148',
    projectId: 'chatting-app-flutter-be3fd',
    storageBucket: 'chatting-app-flutter-be3fd.firebasestorage.app',
    iosBundleId: 'com.example.chattingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSkcWoT0ojKPctWfcJwSinXbDiFlJPNA0',
    appId: '1:839283635148:web:3a07015afa892f7a782369',
    messagingSenderId: '839283635148',
    projectId: 'chatting-app-flutter-be3fd',
    authDomain: 'chatting-app-flutter-be3fd.firebaseapp.com',
    storageBucket: 'chatting-app-flutter-be3fd.firebasestorage.app',
    measurementId: 'G-S588W8PYDQ',
  );
}
